name: SVG zu PNG exportieren

on:
  push:
    paths:
      - '**.svg'
  workflow_dispatch:

jobs:
  export-svg-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Inkscape installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: SVG-Dateien finden und exportieren
        id: find-and-export
        run: |
          mkdir -p exports
          export_count=0
          
          if [[ "${{ github.event_name }}" == "push" ]]; then
            changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.svg$')
          else
            changed_files=$(find . -type f -name "*.svg")
          fi
          
          if [[ -z "$changed_files" ]]; then
            echo "Keine SVG-Dateien für den Export gefunden."
            echo "export_count=0" >> "$GITHUB_ENV"
            exit 0
          fi

          for svg_file in $changed_files; do
            echo "Verarbeite Datei: ${svg_file}"
            base_name=$(basename "${svg_file}" .svg)
            output_dir="exports/${base_name}"
            mkdir -p "${output_dir}"

            for page in $(seq 1 100); do
              output_file="${output_dir}/page_${page}.png"
              
              inkscape --export-type="png" \
                       --export-dpi=300 \
                       --export-background-opacity=0 \
                       --export-area-page \
                       -p "${page}" \
                       -o "${output_file}" \
                       "${svg_file}" &> /dev/null
              
              # Überprüfe, ob die exportierte Datei existiert und eine Mindestgröße hat
              # 1 Kilobyte ist ein sicherer Wert, um leere oder fehlerhafte PNGs auszuschließen
              if [ -s "${output_file}" ] && [ $(stat -c%s "${output_file}") -gt 1024 ]; then
                echo "Seite ${page} exportiert."
                export_count=$((export_count + 1))
              else
                echo "Keine weiteren Seiten für ${svg_file} gefunden oder Fehler beim Export von Seite ${page}."
                rm -f "${output_file}" # Lösche die fehlerhafte Datei
                break
              fi
            done
          done
          echo "Gesamt exportierte Seiten: $export_count"
          echo "export_count=$export_count" >> "$GITHUB_ENV"

      - name: Änderungen committen und pushen
        if: env.export_count > '0'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Automatisch exportierte PNGs aus SVG-Dateien"
          file_pattern: "exports/**/*.png"
          repository: .
