name: SVG zu PNG exportieren

on:
  push:
    paths:
      - '**.svg'
  workflow_dispatch:

jobs:
  export-svg-pages:
    runs-on: ubuntu-latest
    
    container:
      image: alpine/inkscape:1.3.2
      options: --user root

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Inkscape Version prüfen
        run: inkscape --version

      - name: SVG-Dateien finden und exportieren
        id: find-and-export
        shell: bash
        run: |
          mkdir -p exports
          export_count=0
          
          if [ "${{ github.event_name }}" == "push" ]; then
            changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.svg$')
          else
            changed_files=$(find . -type f -name "*.svg")
          fi
          
          if [ -z "$changed_files" ]; then
            echo "Keine SVG-Dateien für den Export gefunden."
            echo "export_count=0" >> "$GITHUB_ENV"
            exit 0
          fi

          for svg_file in $changed_files; do
            echo "Verarbeite Datei: ${svg_file}"
            base_name=$(basename "${svg_file}" .svg)
            output_dir="exports"
            output_file="${output_dir}/${base_name}.png"

            inkscape --export-type="png" \
                     --export-dpi=300 \
                     --export-background-opacity=0 \
                     --export-area-page \
                     -o "${output_file}" \
                     "${svg_file}" &> /dev/null
            
            if [ -s "${output_file}" ]; then
              file_size=$(stat -c%s "${output_file}")
              if [ "$file_size" -gt 1024 ]; then
                echo "Datei ${base_name}.png erfolgreich exportiert. (Größe: $file_size Bytes)"
                export_count=$((export_count + 1))
              else
                echo "Export von ${base_name}.png fehlgeschlagen oder leere Datei erstellt (Größe: $file_size Bytes). Datei wurde gelöscht."
                rm -f "${output_file}"
              fi
            else
              echo "Export von ${base_name}.png fehlgeschlagen. Ausgabedatei existiert nicht."
            fi
          done
          
          echo "Gesamt exportierte Seiten: $export_count"
          echo "export_count=$export_count" >> "$GITHUB_ENV"

      - name: Änderungen committen und pushen
        if: env.export_count > '0'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Automatisch exportierte PNGs aus SVG-Dateien"
          file_pattern: "exports/*.png"
          repository: .
